using System.Collections.Generic;
using ArenaForge.Core;
using ArenaForge.Editor;
using ArenaForge.Unity;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace ArenaForge.Tests
{
    /// <summary>
    /// The building loop end to end: generate it in a scene, re-roll one floor, bake it into a
    /// prefab, and find the arena generator placing it with nothing in the arena generator having
    /// changed.
    /// </summary>
    /// <remarks>
    /// The last of those is the point of the export, and it is the one that would fail quietly.
    /// If placing an exported building had needed a special case in <c>ArenaLayoutGenerator</c>,
    /// the catalog boundary would have a hole in it — so the map here is generated by exactly the
    /// same call a map has always been generated by, against a catalog that happens to have one
    /// more row in it.
    /// </remarks>
    public sealed class BuildingWorkflowTests
    {
        const string TempFolder = "Assets/ArenaForgeBuildingTestTemp";
        const string ExportPath = TempFolder + "/exported_building.prefab";

        CatalogAsset _catalog;
        ArenaBuilding _building;

        [SetUp]
        public void SetUp()
        {
            if (!AssetDatabase.IsValidFolder(TempFolder))
            {
                AssetDatabase.CreateFolder("Assets", "ArenaForgeBuildingTestTemp");
            }

            _catalog = ScriptableObject.CreateInstance<CatalogAsset>();
            _catalog.SetRows(new List<CatalogAsset.Row>
            {
                Row("marker/spawn", new[] { "marker", "spawn" }, new Vector2(2f, 2f), 0.5f),
                Row("structure/building/two_storey_01", new[] { "structure", "structure/building" },
                    new Vector2(12f, 10f), 6f),
                Row("structure/house/small_01", new[] { "structure", "structure/house" },
                    new Vector2(8f, 6f), 3.5f),
                Row("cover/low/crate_wood_01", new[] { "cover", "cover/low" }, new Vector2(1f, 1f), 1f),
                Row("cover/high/barrier_concrete_01", new[] { "cover", "cover/high" },
                    new Vector2(2f, 0.5f), 1.8f),

                // The clutter a room's floor is scattered with, which is a different folder and a
                // different tag from the arena's cover above — see BuildingGenerator.InteriorCoverTag.
                // A building needs it; a map does not, and this fixture has to generate both.
                Row(
                    "propbuilding/decor/interiorcovers/boxes_01",
                    new[] { "propbuilding", "propbuilding/decor", BuildingGenerator.InteriorCoverTag },
                    new Vector2(1f, 1f),
                    1f),
            });

            var host = new GameObject("ArenaForge Test Building");
            host.AddComponent<WorldRealizer>().Catalog = _catalog;
            _building = host.AddComponent<ArenaBuilding>();
            _building.Seed = 20260816UL;
        }

        [TearDown]
        public void TearDown()
        {
            if (_building != null)
            {
                Object.DestroyImmediate(_building.gameObject);
            }

            if (_catalog != null)
            {
                Object.DestroyImmediate(_catalog);
            }

            AssetDatabase.DeleteAsset(TempFolder);
        }

        CatalogAsset.Row Row(string logicalId, string[] tags, Vector2 footprint, float height)
        {
            var source = GameObject.CreatePrimitive(PrimitiveType.Cube);
            string path = $"{TempFolder}/{logicalId.Replace('/', '_')}.prefab";
            GameObject prefab = PrefabUtility.SaveAsPrefabAsset(source, path);
            Object.DestroyImmediate(source);

            return new CatalogAsset.Row
            {
                LogicalId = logicalId,
                Tags = tags,
                FootprintSize = footprint,
                Height = height,
                Weight = 1f,
                Prefab = prefab,
            };
        }

        // --- the loop -------------------------------------------------------------------------

        [Test]
        public void GeneratingRealisesOneGameObjectPerResolvedObject()
        {
            ResolvedWorld resolved = _building.Generate();

            Assert.That(resolved.Objects, Is.Not.Empty);
            Assert.That(_building.Realizer.RealizedCount, Is.EqualTo(resolved.Objects.Count));
            Assert.That(_building.GeneratedFloorCount, Is.EqualTo(_building.FloorCount));
        }

        [Test]
        public void TheDocumentSurvivesTheRoundTripThroughTheComponent()
        {
            _building.Generate();
            string before = ArenaJson.SerializeBuilding(_building.Document);

            // What a scene reload does: the object graph is gone, only the string is left.
            _building.SetDocument(ArenaJson.DeserializeBuilding(before));

            Assert.That(ArenaJson.SerializeBuilding(_building.Document), Is.EqualTo(before));
        }

        [Test]
        public void RerollingOneFloorThroughTheComponentLeavesTheOthersAlone()
        {
            _building.Generate();
            string first = FloorSignature(0);
            string second = FloorSignature(1);
            string third = FloorSignature(2);

            _building.RerollFloor(1, 987654321UL);

            Assert.That(FloorSignature(0), Is.EqualTo(first));
            Assert.That(FloorSignature(2), Is.EqualTo(third));
            Assert.That(FloorSignature(1), Is.Not.EqualTo(second));
        }

        [Test]
        public void RegeneratingKeepsTheFloorSeedsSoOnlyTheParameterChangeShows()
        {
            _building.Generate();
            List<ulong> before = FloorSeeds();

            _building.ContentDensity = 0.5f;
            _building.Regenerate();

            Assert.That(FloorSeeds(), Is.EqualTo(before),
                "a regeneration is not a re-roll — the floors keep the seeds they had");
        }

        [Test]
        public void ClearDropsTheDocumentAndTheRealisedObjects()
        {
            _building.Generate();
            Assert.That(_building.Realizer.RealizedCount, Is.GreaterThan(0));

            _building.Clear();

            Assert.That(_building.HasDocument, Is.False);
            Assert.That(_building.Realizer.RealizedCount, Is.Zero);
        }

        [Test]
        public void ABuildingOperationCollapsesIntoOneNamedUndoStep()
        {
            MapOperationResult result = MapOperations.Run(
                _building, "generate building", b => b.Generate());

            Assert.That(result.Succeeded, Is.True, result.Error);
            Assert.That(Undo.GetCurrentGroupName(), Is.EqualTo("ArenaForge: generate building"));

            Undo.PerformUndo();

            Assert.That(_building.HasDocument, Is.False, "one undo walks the whole generation back");
            Assert.That(_building.Realizer.RealizedCount, Is.Zero, "and the GameObjects with it");
        }

        // --- export ---------------------------------------------------------------------------

        /// <remarks>
        /// The art, counted without the doorway markers the export bakes in beside it. A marker is
        /// an annotation and not an object the document placed — the same reason
        /// <c>CatalogSync.TryMeasure</c> steps over its collider — so what this asserts is that
        /// every resolved object reached the prefab and nothing else did.
        /// </remarks>
        [Test]
        public void TheExportedPrefabHoldsExactlyTheResolvedObjects()
        {
            ResolvedWorld resolved = _building.Generate();

            GameObject prefab = BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            Assert.That(prefab, Is.Not.Null);
            Assert.That(
                prefab.transform.childCount - DoorwaySetup.MarkersIn(prefab).Count,
                Is.EqualTo(resolved.Objects.Count));
        }

        /// <remarks>
        /// An exported building is a leaf: baked art, no longer re-rollable by floor. The
        /// <see cref="ArenaObjectRef"/> components name objects in a document that no longer
        /// governs the prefab carrying them, so they come off on the way out.
        /// </remarks>
        [Test]
        public void TheExportedPrefabCarriesNoDocumentReferences()
        {
            _building.Generate();

            GameObject prefab = BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            Assert.That(prefab.GetComponentsInChildren<ArenaObjectRef>(true), Is.Empty);
        }

        [Test]
        public void TheCatalogRowMatchesTheBuildingsBounds()
        {
            _building.Generate();
            BuildingDoc doc = _building.Document;

            BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            CatalogAsset.Row row = FindRow("structure/building/exported");
            Assert.That(row, Is.Not.Null, "the export added no catalog row");
            Assert.That(row.FootprintSize.x, Is.EqualTo(doc.Footprint.Width).Within(1e-4f));
            Assert.That(row.FootprintSize.y, Is.EqualTo(doc.Footprint.Depth).Within(1e-4f));
            Assert.That(row.Height, Is.EqualTo(doc.Height).Within(1e-4f));
            Assert.That(row.Height, Is.EqualTo(_building.FloorCount * _building.FloorHeight).Within(1e-4f),
                "height comes from the floors");
            Assert.That(row.Tags, Does.Contain(ArenaLayoutGenerator.BuildingTag));
        }

        [Test]
        public void ExportingTwiceReplacesTheRowRatherThanDuplicatingIt()
        {
            _building.Generate();

            BuildingExport.Export(_building, "structure/building/exported", ExportPath);
            int after = CountRows("structure/building/exported");
            BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            Assert.That(after, Is.EqualTo(1));
            Assert.That(CountRows("structure/building/exported"), Is.EqualTo(1));
        }

        [Test]
        public void ExportingSomethingThatHasNotBeenGeneratedIsRefused()
        {
            Assert.Throws<System.InvalidOperationException>(
                () => BuildingExport.Export(_building, "structure/building/exported", ExportPath));
        }

        // --- doorways -----------------------------------------------------------------------

        /// <remarks>
        /// <para>
        /// A single storey is the quickest building to make and the one whose export had nothing to
        /// say about its doors. Where a map keeps the ground clear in front of a structure is
        /// decided by what the row declares, so a row with an empty list is a house the cover stage
        /// stacks crates against the front door of.
        /// </para>
        /// <para>
        /// One storey and no more, because that is the shape the failure was reported in and
        /// because a ground floor is where every entrance is: the storey above has none to declare,
        /// so a building of one floor declares everything a building of three does.
        /// </para>
        /// </remarks>
        [Test]
        public void ASingleStoreyBuildingExportsTheDoorwaysItsGroundFloorDeclares()
        {
            AddShellArt();
            _building.FloorCount = 1;
            _building.Generate();

            List<Rect2> declared = Declared(_building.Document);
            Assert.That(declared, Is.Not.Empty, "the fixture built a ground floor with no way in");

            BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            CatalogAsset.Row row = FindRow("structure/building/exported");
            Assert.That(row.Doorways.Count, Is.EqualTo(declared.Count));

            for (int i = 0; i < declared.Count; i++)
            {
                Assert.That(row.Doorways[i].Center.x, Is.EqualTo(declared[i].Center.X).Within(1e-4f));
                Assert.That(row.Doorways[i].Center.y, Is.EqualTo(declared[i].Center.Y).Within(1e-4f));
                Assert.That(row.Doorways[i].Size.x, Is.EqualTo(declared[i].Width).Within(1e-4f));
                Assert.That(row.Doorways[i].Size.y, Is.EqualTo(declared[i].Depth).Within(1e-4f));
            }
        }

        /// <remarks>
        /// <para>
        /// The document a scene has been holding since before there was any metadata to hold. The
        /// openings were only ever written down once the map learned to believe a structure about
        /// them, so a building generated before that and never regenerated says nothing — and the
        /// reader turned that into a row with no doorways and no complaint, which is the failure
        /// nobody could see: the prefab is right, the row looks right, and only the maps built from
        /// it are wrong.
        /// </para>
        /// <para>
        /// The metadata is stripped rather than a stale fixture being committed, because what is
        /// being asserted is the export's behaviour when the document is silent, and a document
        /// with the keys taken out is exactly that whatever wrote it.
        /// </para>
        /// </remarks>
        [Test]
        public void ADocumentThatDeclaresNoDoorwaysStillExportsItsGroundFloorsOwn()
        {
            AddShellArt();
            _building.FloorCount = 1;
            _building.Generate();

            List<Rect2> declared = Declared(_building.Document);
            _building.SetDocument(WithoutDoorwayMetadata(_building.Document));
            Assert.That(Declared(_building.Document), Is.Empty, "the metadata was not stripped");

            BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            CatalogAsset.Row row = FindRow("structure/building/exported");
            Assert.That(row.Doorways.Count, Is.EqualTo(declared.Count));

            for (int i = 0; i < declared.Count; i++)
            {
                Assert.That(row.Doorways[i].Center.x, Is.EqualTo(declared[i].Center.X).Within(1e-4f));
                Assert.That(row.Doorways[i].Center.y, Is.EqualTo(declared[i].Center.Y).Within(1e-4f));
            }
        }

        /// <remarks>
        /// <para>
        /// <strong>The prefab has to say it too, and not only the row.</strong> A row is a fact
        /// about a catalog and a marker is a fact about the asset, and until the export baked them
        /// the building declared its doors in the one place that could be thrown away. Remove the
        /// row — tidying up, rebuilding a catalog from scratch — and the doorways went with it, so
        /// what a map got back was a house it guessed the middle of two faces for.
        /// </para>
        /// <para>
        /// An ordinary marker, asserted the way an imported house's is: found by the name
        /// <c>CatalogSync</c> matches on, and carrying a trigger box the size of the opening. The
        /// point is that there is no second kind of marker, so what is checked here is the shape
        /// <see cref="DoorwaySetup"/> writes by hand.
        /// </para>
        /// </remarks>
        [Test]
        public void TheExportedPrefabCarriesADoorwayMarkerForEachDoorway()
        {
            AddShellArt();
            _building.FloorCount = 1;
            _building.Generate();

            List<Rect2> declared = Declared(_building.Document);
            Assert.That(declared, Is.Not.Empty, "the fixture built a ground floor with no way in");

            GameObject prefab = BuildingExport.Export(
                _building, "structure/building/exported", ExportPath);

            List<Transform> markers = DoorwaySetup.MarkersIn(prefab);
            Assert.That(markers.Count, Is.EqualTo(declared.Count));

            for (int i = 0; i < declared.Count; i++)
            {
                Assert.That(markers[i].name, Does.StartWith(CatalogSync.DoorwayMarkerName));
                Assert.That(markers[i].parent, Is.EqualTo(prefab.transform));

                var box = markers[i].GetComponent<BoxCollider>();
                Assert.That(box, Is.Not.Null, $"'{markers[i].name}' has no box to measure");
                Assert.That(box.isTrigger, Is.True, "a marker is an annotation, not collision");

                Assert.That(markers[i].localPosition.x,
                    Is.EqualTo(declared[i].Center.X).Within(1e-4f));
                Assert.That(markers[i].localPosition.z,
                    Is.EqualTo(declared[i].Center.Y).Within(1e-4f));
                Assert.That(box.size.x, Is.EqualTo(declared[i].Width).Within(1e-4f));
                Assert.That(box.size.z, Is.EqualTo(declared[i].Depth).Within(1e-4f));
            }
        }

        /// <remarks>
        /// <para>
        /// The failure the markers exist for, run end to end. Somebody deletes an exported
        /// building's row and presses <em>Sync from Folders</em>, which is the ordinary way to get
        /// art the catalog has lost back into it — and what came back was the same prefab with a
        /// doorway count of zero, because the scan asks the asset and the asset had never been
        /// told. Nothing anywhere reported it: the prefab is right, the row looks right, and only
        /// the maps built from it are wrong.
        /// </para>
        /// <para>
        /// The building is exported into a subfolder, because that is what gives a scanned prefab
        /// its tags — a prefab sitting in the root of the scanned folder is skipped for having
        /// nothing to say what it is.
        /// </para>
        /// </remarks>
        [Test]
        public void ABuildingTheCatalogHasLostComesBackFromItsFolderWithItsDoorways()
        {
            AddShellArt();
            _building.FloorCount = 1;
            _building.Generate();

            AssetDatabase.CreateFolder(TempFolder, "Buildings");
            BuildingExport.Export(
                _building, "structure/building/exported", TempFolder + "/Buildings/Exported.prefab");

            int exported = FindRow("structure/building/exported").Doorways.Count;
            Assert.That(exported, Is.Not.Zero, "the export declared no doorways to lose");

            DropRow("structure/building/exported");

            CatalogSync.Sync(_catalog, TempFolder);

            CatalogAsset.Row row = FindRow("structure/building/exported");
            Assert.That(row, Is.Not.Null, "the sync did not bring the building back");
            Assert.That(row.Doorways.Count, Is.EqualTo(exported),
                "the building came back without the doors it was exported with");
        }

        /// <summary>The same document with every doorway key taken out of its metadata.</summary>
        static BuildingDoc WithoutDoorwayMetadata(BuildingDoc doc)
        {
            BuildingDoc stripped = ArenaJson.DeserializeBuilding(ArenaJson.SerializeBuilding(doc));
            var keys = new List<string>(stripped.Metadata.Keys);

            for (int i = 0; i < keys.Count; i++)
            {
                if (keys[i].StartsWith(
                        BuildingGenerator.DoorwayKeyPrefix, System.StringComparison.Ordinal) ||
                    keys[i] == BuildingGenerator.DoorwayCountKey)
                {
                    stripped.Metadata.Remove(keys[i]);
                }
            }

            return stripped;
        }

        /// <summary>The doorway rectangles a document's metadata declares, in metadata order.</summary>
        static List<Rect2> Declared(BuildingDoc doc)
        {
            var doorways = new List<Rect2>();
            if (!doc.Metadata.TryGetValue(BuildingGenerator.DoorwayCountKey, out string countText) ||
                !int.TryParse(countText, out int count))
            {
                return doorways;
            }

            for (int i = 0; i < count; i++)
            {
                doorways.Add(RectMetadata.Parse(
                    doc.Metadata[BuildingGenerator.DoorwayKeyPrefix + i.ToString("00")]));
            }

            return doorways;
        }

        /// <summary>
        /// Adds the shell art a floor needs before it has an outside wall to take a door out of.
        /// </summary>
        /// <remarks>
        /// Not in the fixture's own catalog, because a building with walls is a different building:
        /// every other test in this file measures the one the bare catalog makes, and giving them
        /// all a shell would move counts and playability for reasons that have nothing to do with
        /// what they assert. The wall stands under the default floor height less the slab, which is
        /// what <c>BuildingGenerator.SelectShell</c> requires of it.
        /// </remarks>
        void AddShellArt()
        {
            var rows = new List<CatalogAsset.Row>(_catalog.Rows)
            {
                Row("structure/floor/slab_1m", new[] { "structure", "structure/floor" },
                    new Vector2(1f, 1f), 0.2f),
                Row("structure/wall/panel_2m", new[] { "structure", "structure/wall" },
                    new Vector2(2f, 0.2f), 2.5f),
                Row("structure/doorway/frame_2m", new[] { "structure", "structure/doorway" },
                    new Vector2(2f, 0.2f), 2.5f),
            };

            _catalog.SetRows(rows);
        }

        // --- and back into a map ----------------------------------------------------------------

        /// <remarks>
        /// The acceptance criterion, and the reason the export writes a catalog row rather than
        /// doing anything to the arena generator: this calls <c>ArenaLayoutGenerator.Generate</c>
        /// exactly as every other map test does.
        /// </remarks>
        [Test]
        public void AMapPlacesAnExportedBuildingAndStaysPlayable()
        {
            _building.Generate();
            BuildingExport.Export(_building, "structure/building/exported", ExportPath);

            // Only the exported building is left tagged structure/building, so the middle-lane
            // slot has no choice but to select it.
            DropRow("structure/building/two_storey_01");

            var host = new GameObject("ArenaForge Test Map");
            try
            {
                host.AddComponent<WorldRealizer>().Catalog = _catalog;
                ArenaMap map = host.AddComponent<ArenaMap>();
                map.Seed = 20260816UL;

                ResolvedWorld resolved = map.Generate();

                Assert.That(Placed(resolved, "structure/building/exported"), Is.True,
                    "the map did not place the exported building");
                Assert.That(map.Realizer.RealizedCount, Is.EqualTo(resolved.Objects.Count));

                MapReport report = MapAnalyzer.Analyze(map.Document, _catalog.ToCatalog());
                Assert.That(report.IsPlayable, Is.True, report.Describe());
            }
            finally
            {
                Object.DestroyImmediate(host);
            }
        }

        // --- helpers --------------------------------------------------------------------------

        static bool Placed(ResolvedWorld resolved, string logicalId)
        {
            for (int i = 0; i < resolved.Objects.Count; i++)
            {
                if (resolved.Objects[i].LogicalId == logicalId)
                {
                    return true;
                }
            }

            return false;
        }

        List<ulong> FloorSeeds()
        {
            var seeds = new List<ulong>();
            IReadOnlyList<BuildingFloor> floors = _building.Document.Floors;
            for (int i = 0; i < floors.Count; i++)
            {
                seeds.Add(floors[i].Seed);
            }

            return seeds;
        }

        /// <summary>One floor's stored seed and everything on it, as one comparable string.</summary>
        string FloorSignature(int floor)
        {
            BuildingDoc doc = _building.Document;
            var text = new System.Text.StringBuilder();
            text.Append(doc.Floors[floor].Seed).Append('|');

            string prefix = BuildingDoc.FloorIdPrefix(floor) + "/";
            for (int i = 0; i < doc.GeneratedObjects.Count; i++)
            {
                PlacedObject placed = doc.GeneratedObjects[i];
                if (placed.StableId.StartsWith(prefix, System.StringComparison.Ordinal))
                {
                    text.Append(placed.StableId).Append('@').Append(placed.LogicalId)
                        .Append('@').Append(placed.Pose).Append(';');
                }
            }

            return text.ToString();
        }

        CatalogAsset.Row FindRow(string logicalId)
        {
            for (int i = 0; i < _catalog.Rows.Count; i++)
            {
                if (_catalog.Rows[i].LogicalId == logicalId)
                {
                    return _catalog.Rows[i];
                }
            }

            return null;
        }

        int CountRows(string logicalId)
        {
            int count = 0;
            for (int i = 0; i < _catalog.Rows.Count; i++)
            {
                if (_catalog.Rows[i].LogicalId == logicalId)
                {
                    count++;
                }
            }

            return count;
        }

        void DropRow(string logicalId)
        {
            var rows = new List<CatalogAsset.Row>();
            for (int i = 0; i < _catalog.Rows.Count; i++)
            {
                if (_catalog.Rows[i].LogicalId != logicalId)
                {
                    rows.Add(_catalog.Rows[i]);
                }
            }

            _catalog.SetRows(rows);
        }
    }
}
