using System;
using ArenaForge.Core;
using UnityEngine;

namespace ArenaForge.Unity
{
    /// <summary>
    /// A building in a scene: the parameters it is generated from, and the document those
    /// parameters and the per-floor seeds have produced.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The same bargain <see cref="ArenaMap"/> makes, for the same reasons: the document is held
    /// as its serialised JSON so Unity can put it in a scene and snapshot it for undo, and the
    /// realised GameObjects are rebuilt from it rather than being state of their own.
    /// </para>
    /// <para>
    /// It is a sibling of <see cref="ArenaMap"/> rather than a subclass or a mode of it. The two
    /// hold different documents, take different parameters and are generated by different
    /// generators; what they share is the realiser they both drive, which is a component they
    /// both require rather than anything either of them owns.
    /// </para>
    /// </remarks>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(WorldRealizer))]
    [AddComponentMenu("ArenaForge/Arena Building")]
    public sealed class ArenaBuilding : MonoBehaviour
    {
        [SerializeField]
        [Tooltip("The floor seeds are first derived from this. Re-rolling a floor overwrites its own.")]
        ulong _seed = 20260816;

        [SerializeField]
        [Tooltip("Ground footprint in metres, X by Z.")]
        Vector2 _footprintSize = new Vector2(12f, 10f);

        [SerializeField]
        [Min(1)]
        int _floorCount = 3;

        // 3.1 rather than 3, so the 2.9 m wall art in the box fits under the 0.2 m slab beside it.
        // See BuildingParams.FloorHeight: a storey that refuses its own wall art has no envelope.
        [SerializeField]
        [Min(0.1f)]
        [Tooltip("Also the headroom a floor's contents must fit under.")]
        float _floorHeight = 3.1f;

        [SerializeField]
        [Min(0.05f)]
        float _gridSize = 0.5f;

        [SerializeField]
        [Min(0f)]
        [Tooltip("Clear floor kept between the contents and the outside walls.")]
        float _wallMargin = 0.5f;

        [SerializeField]
        [Min(0f)]
        [Tooltip("How much to put on a floor, as a multiple of the baseline density.")]
        float _contentDensity = 1f;

        // Hidden for the reason ArenaMap's is: a document in an inspector field is noise.
        [SerializeField]
        [HideInInspector]
        string _buildingJson;

        [NonSerialized]
        BuildingDoc _document;

        [NonSerialized]
        string _documentJson;

        /// <summary>Seed the initial floor seeds are derived from.</summary>
        public ulong Seed
        {
            get => _seed;
            set => _seed = value;
        }

        /// <summary>Ground footprint in metres, X by Z.</summary>
        public Vector2 FootprintSize
        {
            get => _footprintSize;
            set => _footprintSize = value;
        }

        /// <summary>Number of storeys the next generation will build.</summary>
        public int FloorCount
        {
            get => _floorCount;
            set => _floorCount = value;
        }

        /// <summary>Vertical distance between one floor's ground and the next, in metres.</summary>
        public float FloorHeight
        {
            get => _floorHeight;
            set => _floorHeight = value;
        }

        /// <summary>Placement grid resolution in metres.</summary>
        public float GridSize
        {
            get => _gridSize;
            set => _gridSize = value;
        }

        /// <summary>Clear floor kept between the contents and the outside walls, in metres.</summary>
        public float WallMargin
        {
            get => _wallMargin;
            set => _wallMargin = value;
        }

        /// <summary>How much to put on a floor, as a multiple of the baseline density.</summary>
        public float ContentDensity
        {
            get => _contentDensity;
            set => _contentDensity = value;
        }

        /// <summary>The realiser that turns this building's document into GameObjects.</summary>
        public WorldRealizer Realizer => GetComponent<WorldRealizer>();

        /// <summary>True if this building has been generated.</summary>
        public bool HasDocument => !string.IsNullOrEmpty(_buildingJson);

        /// <summary>
        /// The number of storeys the document actually holds, which is what a per-floor re-roll
        /// indexes into. Zero before the first generation.
        /// </summary>
        /// <remarks>
        /// Not the same thing as <see cref="FloorCount"/>: that is the parameter the <em>next</em>
        /// generation will use, and between changing it and pressing Regenerate the two disagree.
        /// </remarks>
        public int GeneratedFloorCount
        {
            get
            {
                BuildingDoc doc = Document;
                return doc != null ? doc.Floors.Count : 0;
            }
        }

        /// <summary>The document this building holds, or null if it has none yet.</summary>
        /// <exception cref="UnsupportedSchemaVersionException">The stored document is of a schema this build does not read.</exception>
        public BuildingDoc Document
        {
            get
            {
                if (string.IsNullOrEmpty(_buildingJson))
                {
                    _document = null;
                    _documentJson = null;
                    return null;
                }

                if (_document == null || !string.Equals(_documentJson, _buildingJson, StringComparison.Ordinal))
                {
                    _document = ArenaJson.DeserializeBuilding(_buildingJson);
                    _documentJson = _buildingJson;
                }

                return _document;
            }
        }

        /// <summary>Stores a document, or clears the building when given null.</summary>
        public void SetDocument(BuildingDoc doc)
        {
            _buildingJson = doc != null ? ArenaJson.SerializeBuilding(doc) : string.Empty;
            _document = doc;
            _documentJson = _buildingJson;
        }

        /// <summary>The parameters the fields on this component describe.</summary>
        public BuildingParams BuildParams() => new BuildingParams
        {
            Seed = _seed,
            FootprintSize = new Vec2(_footprintSize.x, _footprintSize.y),
            FloorCount = _floorCount,
            FloorHeight = _floorHeight,
            GridSize = _gridSize,
            WallMargin = _wallMargin,
            ContentDensity = _contentDensity,
        };

        /// <summary>Copies a parameter set onto this component's fields.</summary>
        /// <exception cref="ArgumentNullException"><paramref name="parameters"/> is null.</exception>
        public void ApplyParams(BuildingParams parameters)
        {
            if (parameters == null)
            {
                throw new ArgumentNullException(nameof(parameters));
            }

            _seed = parameters.Seed;
            _footprintSize = new Vector2(parameters.FootprintSize.X, parameters.FootprintSize.Y);
            _floorCount = parameters.FloorCount;
            _floorHeight = parameters.FloorHeight;
            _gridSize = parameters.GridSize;
            _wallMargin = parameters.WallMargin;
            _contentDensity = parameters.ContentDensity;
        }

        /// <summary>
        /// Generates a building from the current parameters, deriving every floor seed afresh and
        /// discarding any edits, then realises it.
        /// </summary>
        /// <exception cref="InvalidOperationException">The realiser has no catalog.</exception>
        [ContextMenu("Generate")]
        public ResolvedWorld Generate()
        {
            SetDocument(BuildingGenerator.Generate(BuildParams(), RequireCatalog()));
            return Realize();
        }

        /// <summary>
        /// Generates again, keeping the floor seeds the document already holds and re-applying the
        /// existing edits on top.
        /// </summary>
        /// <remarks>
        /// Keeping the floor seeds is what makes this a regeneration rather than a new building:
        /// change the content density and every floor is re-filled from the seed it already had,
        /// so the change you see is the density's and not the seed's.
        /// </remarks>
        /// <exception cref="InvalidOperationException">The realiser has no catalog.</exception>
        [ContextMenu("Regenerate")]
        public ResolvedWorld Regenerate()
        {
            BuildingDoc previous = Document;
            BuildingDoc doc = BuildingGenerator.Generate(
                BuildParams(), RequireCatalog(), previous != null ? previous.Floors : null);

            if (previous != null)
            {
                for (int i = 0; i < previous.Overrides.Count; i++)
                {
                    doc.Overrides.Add(previous.Overrides[i]);
                }
            }

            SetDocument(doc);
            return Realize();
        }

        /// <summary>
        /// Replaces one floor's seed and generates again, leaving every other floor exactly as it
        /// was.
        /// </summary>
        /// <remarks>
        /// The seed is passed in rather than drawn here, so this component holds no clock-based
        /// randomness and the operation can be tested with a fixed value. The overlay supplies
        /// one from <c>MapOperations.RandomSeed</c>, which is where the map's own seed re-roll
        /// gets its number too.
        /// </remarks>
        /// <exception cref="InvalidOperationException">The building has not been generated, or the realiser has no catalog.</exception>
        /// <exception cref="ArgumentOutOfRangeException"><paramref name="index"/> is not a floor of this building.</exception>
        public ResolvedWorld RerollFloor(int index, ulong seed)
        {
            BuildingDoc previous = Document;
            if (previous == null)
            {
                throw new InvalidOperationException(
                    $"'{name}' has not been generated yet, so it has no floor to re-roll.");
            }

            // The parameters come from the document rather than the component, because a re-roll
            // is a change to one floor: rebuilding with an edited footprint still sitting in the
            // inspector would change the whole building and call it a re-roll.
            BuildingParams parameters = previous.Parameters.Clone();
            BuildingDoc doc = BuildingGenerator.Generate(
                parameters,
                RequireCatalog(),
                BuildingGenerator.WithRerolledFloor(previous.Floors, index, seed));

            for (int i = 0; i < previous.Overrides.Count; i++)
            {
                doc.Overrides.Add(previous.Overrides[i]);
            }

            SetDocument(doc);
            return Realize();
        }

        /// <summary>Realises the document this building holds, replacing whatever is in the scene.</summary>
        public ResolvedWorld Realize()
        {
            BuildingDoc doc = Document;
            if (doc == null)
            {
                Realizer.Derealize();
                return new ResolvedWorld(Array.Empty<PlacedObject>(), Array.Empty<EditOverride>());
            }

            return Realizer.Realize(doc);
        }

        /// <summary>Drops the document and takes the realised building out of the scene.</summary>
        [ContextMenu("Clear")]
        public void Clear()
        {
            Realizer.Derealize();
            SetDocument(null);
        }

        Catalog RequireCatalog()
        {
            CatalogAsset asset = Realizer.Catalog;
            if (asset == null)
            {
                throw new InvalidOperationException(
                    $"'{name}' has no catalog assigned on its World Realizer, so there is nothing to " +
                    "select art from.");
            }

            return asset.ToCatalog();
        }
    }
}
